import { SynthOutput } from 'projen/lib/util/synth';

/**
 * Validates that prettier settings are set properly.
 * @param snapshot Synthesized project output.
 */
export function testSettings(snapshot: SynthOutput, expectedSettings: Record<string, unknown> = {}): void {
  const standardSettings = {
    '//': '~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
    overrides: [
      {
        files: '*.*',
        options: {
          semi: true,
          trailingComma: 'all',
          singleQuote: true,
          printWidth: 120,
          tabWidth: 2,
        },
      },
    ],
  };

  const settings: Record<string, unknown> = Object.keys(expectedSettings).length ? expectedSettings : standardSettings;
  expect(snapshot['.prettierrc.json']).toStrictEqual(settings);
}

/**
 * Validates that ignore patterns matches expected content.
 * @param snapshot Synthesized project output.
 * @param expectedEntries List of entries to test for.
 */
export function testIgnore(snapshot: SynthOutput, expectedEntries: string[] = []): void {
  const standardEntries: string[] = [];
  const entries: string[] = expectedEntries.length ? expectedEntries : standardEntries;
  const content: string[] = snapshot['.prettierignore'].split('\n');
  expect(content.sort()).toEqual(entries.sort());
}
